/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Troll-E.gltf')
  const arr = [1,1,1]
  return (
    <group ref={group} {...props} dispose={null} scale={arr} >
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} />
      <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} />
      <mesh geometry={nodes.Cylinder039.geometry} material={nodes.Cylinder039.material} />
      <mesh geometry={nodes.BezierCurve.geometry} material={nodes.BezierCurve.material} />
      <mesh geometry={nodes.BezierCurve008.geometry} material={nodes.BezierCurve008.material} />
      <mesh geometry={nodes.Cylinder060.geometry} material={nodes.Cylinder060.material} />
      <mesh geometry={nodes.BezierCurve001.geometry} material={nodes.BezierCurve001.material} />
      <mesh geometry={nodes.Cylinder061.geometry} material={nodes.Cylinder061.material} />
      <mesh geometry={nodes.Cylinder020.geometry} material={nodes.Cylinder020.material} />
      <mesh geometry={nodes.Cylinder012.geometry} material={nodes.Cylinder012.material} />
      <mesh geometry={nodes.Cylinder058.geometry} material={nodes.Cylinder058.material} />
      <mesh geometry={nodes.Cylinder053.geometry} material={nodes.Cylinder053.material} />
      <mesh geometry={nodes.Cylinder071.geometry} material={nodes.Cylinder071.material} />
      <mesh geometry={nodes.Cylinder021.geometry} material={nodes.Cylinder021.material} />
      <mesh geometry={nodes.Cylinder055.geometry} material={nodes.Cylinder055.material} />
      <mesh geometry={nodes.Cylinder072.geometry} material={nodes.Cylinder072.material} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} />
      <mesh geometry={nodes.Cylinder024.geometry} material={nodes.Cylinder024.material} />
      <mesh geometry={nodes.BezierCurve033.geometry} material={nodes.BezierCurve033.material} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} />
      <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} />
      <mesh geometry={nodes.Cylinder052.geometry} material={nodes.Cylinder052.material} />
      <mesh geometry={nodes.Cylinder036.geometry} material={nodes.Cylinder036.material} />
      <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} />
      <mesh geometry={nodes.Cylinder042.geometry} material={nodes.Cylinder042.material} />
      <mesh geometry={nodes.Cylinder037.geometry} material={nodes.Cylinder037.material} />
      <mesh geometry={nodes.Cylinder034.geometry} material={nodes.Cylinder034.material} />
      <mesh geometry={nodes.BezierCurve004.geometry} material={nodes.BezierCurve004.material} />
      <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} />
      <mesh geometry={nodes.Cylinder066.geometry} material={nodes.Cylinder066.material} />
      <mesh geometry={nodes.Cylinder063.geometry} material={nodes.Cylinder063.material} />
      <mesh geometry={nodes.Cylinder026.geometry} material={nodes.Cylinder026.material} />
      <mesh geometry={nodes.Cylinder013.geometry} material={nodes.Cylinder013.material} />
      <mesh geometry={nodes.Cylinder056.geometry} material={nodes.Cylinder056.material} />
      <mesh geometry={nodes.BezierCurve020.geometry} material={nodes.BezierCurve020.material} />
      <mesh geometry={nodes.Cylinder059.geometry} material={nodes.Cylinder059.material} />
      <mesh geometry={nodes.Cylinder065.geometry} material={nodes.Cylinder065.material} />
      <mesh geometry={nodes.BezierCurve003.geometry} material={nodes.BezierCurve003.material} />
      <mesh geometry={nodes.Cylinder014.geometry} material={nodes.Cylinder014.material} />
      <mesh geometry={nodes.Cylinder027.geometry} material={nodes.Cylinder027.material} />
      <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} />
      <mesh geometry={nodes.Cylinder030.geometry} material={nodes.Cylinder030.material} />
      <mesh geometry={nodes.Cylinder032.geometry} material={nodes.Cylinder032.material} />
      <mesh geometry={nodes.Cylinder028.geometry} material={nodes.Cylinder028.material} />
      <mesh geometry={nodes.Cylinder010.geometry} material={nodes.Cylinder010.material} />
      <mesh geometry={nodes.Cylinder019.geometry} material={nodes.Cylinder019.material} />
      <mesh geometry={nodes.Cylinder029.geometry} material={nodes.Cylinder029.material} />
      <mesh geometry={nodes.Cylinder031.geometry} material={nodes.Cylinder031.material} />
      <mesh geometry={nodes.Cylinder068.geometry} material={nodes.Cylinder068.material} />
      <mesh geometry={nodes.Cylinder044.geometry} material={nodes.Cylinder044.material} />
      <mesh geometry={nodes.Cylinder047.geometry} material={nodes.Cylinder047.material} />
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} />
      <mesh geometry={nodes.Cylinder046.geometry} material={nodes.Cylinder046.material} />
      <mesh geometry={nodes.Cylinder051.geometry} material={nodes.Cylinder051.material} />
      <mesh geometry={nodes.Cylinder045.geometry} material={nodes.Cylinder045.material} />
      <mesh geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} />
      <mesh geometry={nodes.Cylinder069.geometry} material={nodes.Cylinder069.material} />
      <mesh geometry={nodes.Cylinder048.geometry} material={nodes.Cylinder048.material} />
      <mesh geometry={nodes.Cylinder050.geometry} material={nodes.Cylinder050.material} />
      <mesh geometry={nodes.Cylinder049.geometry} material={nodes.Cylinder049.material} />
      <mesh geometry={nodes.Cylinder054.geometry} material={nodes.Cylinder054.material} />
      <mesh geometry={nodes.Cylinder016.geometry} material={nodes.Cylinder016.material} />
      <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} />
      <mesh geometry={nodes.Cylinder017.geometry} material={nodes.Cylinder017.material} />
      <mesh geometry={nodes.Cylinder057.geometry} material={nodes.Cylinder057.material} />
      <mesh geometry={nodes.Cylinder043.geometry} material={nodes.Cylinder043.material} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} />
      <mesh geometry={nodes.Cylinder064.geometry} material={nodes.Cylinder064.material} />
      <mesh geometry={nodes.Cylinder070.geometry} material={nodes.Cylinder070.material} />
      <mesh geometry={nodes.Cylinder067.geometry} material={nodes.Cylinder067.material} />
      <mesh geometry={nodes.Cylinder033.geometry} material={nodes.Cylinder033.material} />
      <mesh geometry={nodes.Cylinder015.geometry} material={nodes.Cylinder015.material} />
      <mesh geometry={nodes.Cylinder038.geometry} material={nodes.Cylinder038.material} />
      <mesh geometry={nodes.Cylinder041.geometry} material={nodes.Cylinder041.material} />
      <mesh geometry={nodes.Cylinder025.geometry} material={nodes.Cylinder025.material} />
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} />
      <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} />
      <mesh geometry={nodes.BezierCurve009.geometry} material={nodes.BezierCurve009.material} />
      <mesh geometry={nodes.Cylinder018.geometry} material={nodes.Cylinder018.material} />
      <mesh geometry={nodes.Cylinder011.geometry} material={nodes.Cylinder011.material} />
      <mesh geometry={nodes.Cylinder040.geometry} material={nodes.Cylinder040.material} />
      <mesh geometry={nodes.Cylinder022.geometry} material={nodes.Cylinder022.material} />
      <mesh geometry={nodes.Cylinder023.geometry} material={nodes.Cylinder023.material} />
      <mesh geometry={nodes.BezierCurve005.geometry} material={nodes.BezierCurve005.material} />
      <mesh geometry={nodes.Cylinder062.geometry} material={nodes.Cylinder062.material} />
      <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} />
      <mesh geometry={nodes.Cylinder035.geometry} material={nodes.Cylinder035.material} />
      <mesh geometry={nodes.SketchUp.geometry} material={nodes.SketchUp.material} />
      <mesh geometry={nodes.ID61.geometry} material={nodes.ID61.material} />
      <mesh geometry={nodes.ID20.geometry} material={nodes.ID20.material} />
      <mesh geometry={nodes.ID42.geometry} material={nodes.ID42.material} />
      <mesh geometry={nodes.ID30.geometry} material={nodes.ID30.material} />
      <mesh geometry={nodes.ID48.geometry} material={nodes.ID48.material} />
      <mesh geometry={nodes.ID14.geometry} material={nodes.ID14.material} />
      <mesh geometry={nodes.ID36.geometry} material={nodes.ID36.material} />
      <mesh geometry={nodes.Box1.geometry} material={nodes.Box1.material} />
      <mesh geometry={nodes.Camera_corpus.geometry} material={nodes.Camera_corpus.material} />
      <mesh geometry={nodes.Inner_corpuse.geometry} material={nodes.Inner_corpuse.material} />
      <mesh geometry={nodes.Lens_camera.geometry} material={nodes.Lens_camera.material} />
      <mesh geometry={nodes.Box2.geometry} material={nodes.Box2.material} />
      <mesh geometry={nodes.SENSOR.geometry} material={nodes.SENSOR.material} />
      <mesh geometry={nodes.Box.geometry} material={nodes.Box.material} />
      <mesh geometry={nodes.Box3.geometry} material={nodes.Box3.material} />
    </group>
  )
}

useGLTF.preload('/Troll-E.gltf')
